<!DOCTYPE html>
<html class="bg">
<head>
	<meta http-equiv="content-type" content="text/html; charset=windows-1252">
	<title>VETCheck/Best Place for All Pets</title>
	<title>Only place to Fix your Pets</title>



<body>
<div class="page-content">
	<h1>
		<a href="https://hmn.md" class="company">
			<img src="<?php echo get_stylesheet_directory_uri(); ?>/images/hm-logo-white.png" alt="Human Made"/>
		</a>
	</h1>
</div>
</body>
</html>